enforce_secure_profile: false
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 127.0.0.1:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 100
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
log_pings: true
connection_throttle_limit: 0
server_connect_timeout: 500000
timeout: 3000000
stats: 962f574d-6f3f-40f8-9b2a-2c0467a28290
player_limit: -1
ip_forward: true
groups: {}
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: false
forge_support: true
disabled_commands:
- server
servers:
  lobby:
    motd: '&1Just another Waterfall - Forced Host'
    address: uk02.legacynodes.com:2049
    restricted: false
  fastbridge:
    motd: '&1Just another Waterfall - Forced Host'
    address: free6.cortexnodes.com:40190
    restricted: false
  boommc:
    motd: '&1Just another Waterfall - Forced Host'
    address: ruby.magmanode.com:26151
    restricted: false
  practice:
    motd: '&1Just another Waterfall - Forced Host'
    address: n5.mcst.io:35587
    restricted: false
  botpractice:
    motd: '&1Just another Waterfall - Forced Host'
    address: n5.mcst.io:25574
    restricted: false

  
  


